### ISSUE TITLE
BridgingCreator$Companion.getShared

### ISSUE THREAD

**Issue by pam3ec555** [superwall/Superwall-Flutter#10]
Hello, I got an error in my crashlytics from a lot of Android users but couldn't reproduce it locally.

Fatal Exception: java.lang.IllegalStateException: BridgingCreator not initialized
       at com.superwall.superwallkit_flutter.BridgingCreator$Companion.getShared(BridgingCreator.kt:23)
       at com.superwall.superwallkit_flutter.bridges.PaywallInfoBridgeKt.createBridgeId(PaywallInfoBridge.kt:62)
       at SuperwallEventInfo_JsonKt.toJson(SuperwallEventInfo+Json.kt:55)
       at SuperwallEventInfo_JsonKt.toJson(SuperwallEventInfo+Json.kt:9)
       at com.superwall.superwallkit_flutter.bridges.SuperwallDelegateProxyBridge.handleSuperwallEvent(SuperwallDelegateProxyBridge.kt:44)
       at com.superwall.sdk.delegate.SuperwallDelegateAdapter.handleSuperwallEvent(SuperwallDelegateAdapter.kt:48)
       at com.superwall.sdk.analytics.internal.TrackingKt.track(Tracking.kt:48)
       at com.superwall.sdk.analytics.internal.TrackingKt$track$1.invokeSuspend(Tracking.kt:10)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

The error exists on superwallkit_flutter: 1.1.4

**Comment by ianrumac** [comment]
Hi @pam3ec555  !

Thanks for the report and sorry for the issues - we've released an update (1.2.1) that should mitigate these crashes. If you continue seeing them after updating, please feel free to reopen the issue and let us know!

**Comment by mertcanerbasi** [comment]
This error still persists. I cant produce it either but %99 of the time that occurs when app is in background as firebase crashlytics says. 

Error log is there : 

   Fatal Exception: java.lang.IllegalStateException: BridgingCreator not initialized
       at com.superwall.superwallkit_flutter.BridgingCreator$Companion.getShared(:11)
       at com.superwall.superwallkit_flutter.SuperwallkitFlutterPluginKt.bridgeInstance(SourceFile:4)
       at com.superwall.superwallkit_flutter.bridges.SuperwallBridge$onMethodCall$1$14$1$1.invokeSuspend(:39)
       at kotlin.coroutines.jvm.internal.a.resumeWith(:11)
       at X9.X.run(:128)
       at da.n$a.run(:3)
       at fa.k.run(:2)
       at fa.a.Z()
       at fa.a$c.d(:14)
       at fa.a$c.p(:28)
       at fa.a$c.run()
