### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method createBridgeInstance on channel SWK_BridgingCreator)

### ISSUE THREAD

**Issue by devfernandorodrigues** [superwall/Superwall-Flutter#54]
After updating to version 1.3.9, I have this issue:

```
E/flutter (10865): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:31:5)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:45:7)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:136:5)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:85:11)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): #5      Superwall.setSubscriptionStatus (package:superwallkit_flutter/src/public/Superwall.dart:188:18)
E/flutter (10865): <asynchronous suspension>
E/flutter (10865): 
```

**Comment by yusuftor** [comment]
Hi, is this on iOS? We just released an update to fix an issue like this on iOS, please update and let us know if that fixes it.

**Comment by devfernandorodrigues** [comment]
> Hi, is this on iOS? We just released an update to fix an issue like this on iOS, please update and let us know if that fixes it.

I'm having this issue on Android.

Also, I'm having a lot of issues with Superwall, it's crashing on a lot of devices.

```
Exception java.lang.IllegalStateException: BridgingCreator not initialized
  at com.superwall.superwallkit_flutter.BridgingCreator$Companion.getShared (BridgingCreator.kt:33)
  at com.superwall.superwallkit_flutter.SuperwallkitFlutterPluginKt.bridgeInstance (SuperwallkitFlutterPlugin.kt:77)
  at com.superwall.superwallkit_flutter.bridges.SuperwallBridge$onMethodCall$1$17$1$1.invokeSuspend (SuperwallBridge.kt:289)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run (DispatchedTask.kt:104)
  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.kt:111)
  at kotlinx.coroutines.scheduling.TaskImpl.run (Tasks.kt:99)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.kt)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.kt:811)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.kt:715)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.kt)
```

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/937ffb60-853e-4eed-a52a-30c709755048" />

**Comment by yusuftor** [comment]
What version of our SDK are you using?

**Comment by devfernandorodrigues** [comment]
> What version of our SDK are you using?

In production is 1.3.7

**Comment by ianrumac** [comment]
Hi @devfernandorodrigues  - the issue in the screenshot on Android should be solved with version 1.3.9.

Regarding the original issue (one in the first message), could you post the full stacktrace? The actual crash message seems to be cutoff and it would be quite helpful in understanding the issue.

**Comment by devfernandorodrigues** [comment]
> Hi [@devfernandorodrigues](https://github.com/devfernandorodrigues) - the issue in the screenshot on Android should be solved with version 1.3.9.
> 
> Regarding the original issue (one in the first message), could you post the full stacktrace? The actual crash message seems to be cutoff and it would be quite helpful in understanding the issue.

Hi, this is what I have in the debug console.

```
I/flutter ( 3738): [LogLevel.error] Failed to configure Superwall
E/flutter ( 3738): [ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method createBridgeInstance on channel SWK_BridgingCreator)
E/flutter ( 3738): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): #1      BridgingCreator._invokeBridgeInstanceCreation (package:superwallkit_flutter/src/private/BridgingCreator.dart:31:5)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): #2      BridgingCreator._ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:45:7)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): #3      BridgeAdditions.ensureBridgeCreated (package:superwallkit_flutter/src/private/BridgingCreator.dart:136:5)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): #4      MethodChannelBridging.invokeBridgeMethod (package:superwallkit_flutter/src/private/BridgingCreator.dart:85:11)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): #5      Superwall.setSubscriptionStatus (package:superwallkit_flutter/src/public/Superwall.dart:188:18)
E/flutter ( 3738): <asynchronous suspension>
E/flutter ( 3738): 
```

**Comment by ianrumac** [comment]
Hey everyone!
We have just released a new version `1.3.11` that should help mitigate these issues. 
We'll also ship the update to the new 2.0.* SDK soon, so if you're using v2 keep an eye out for that.

Keeping the issue open until we're 100% sure it's been mitigated.

**Comment by lukemmtt** [comment]
Still seeing this error in production, running sdk version 1.3.11.

**Comment by ianrumac** [comment]
Hey everyone, 
thanks for your patience. We have released a new SDK beta (**2.1.0-beta.2**) which contains a rework of the underlying bridges to a safer and more reliable approach. If you still see this or a similar issue pop up after updating, please let us know!
