### ISSUE TITLE
[v2.1.0] Superwall Delegate not sending paywall info

### ISSUE THREAD

**Issue by OrcunJoyoLabs** [superwall/Superwall-Flutter#85]
Hey folks,

I noticed that after moving from 2.0.5 -> 2.1.0, I have lost the paywall information on SuperWall Delegate (only iOS testing).

Sample code below:

```dart
@override
  Future<void> handleSuperwallEvent(SuperwallEventInfo eventInfo) async {
    try {
      final paywallInfo = eventInfo.event.paywallInfo;
      final placementName = eventInfo.event.placementName;
      final product = eventInfo.event.product;

      print('Event name: ${eventInfo.event.type}');
      print('Event Params: ${eventInfo.params}');
      print('Is Paywall info null? ${paywallInfo == null}');
      print('Is Placement name null? ${placementName == null}');
      print('Is Product null? ${eventInfo.event.product == null}');

...
```

Expected:

- Non-null paywall info on paywall open event
- Non-null product info on transaction start
- Non-null placement name in events

Actual Output:

- All values are null (paywallInfo, placementName, product) in both paywallOpen and transactionStart events

> flutter: Event name: EventType.paywallOpen
> flutter: Event Params: null
> flutter: Is Paywall info null? true
> flutter: Is Placement name null? true
> flutter: Is Product null? true

> flutter: Event name: EventType.transactionStart
> flutter: Event Params: null
> flutter: Is Paywall info null? true
> flutter: Is Placement name null? true
> flutter: Is Product null? true

_My flutter version: Flutter 3.29.1, Dart 3.7.0, tested on iOS only, both on simulator and physical device_

**Comment by ianrumac** [comment]
## 2.1.0-beta.1

## Enhancements

- Updates kotlin version to 2.0.21
- Updates `compileSDK` to 35
- Adds web checkout and redemption support
- Adds SuperwallDelegate methods `willRedeemLink` and `didRedeemLink`

**Comment by DaxeshV** [comment]
Same i also reproduce here since few days ago --- https://teams.live.com/l/message/19:638371ef3697a9ad878bdf1f96cc6d17f2583a696b49a0e7ca1703ddea47785d@oneToOne.skype/1746698520108?context=%7B%22contextType%22%3A%22chat%22%7D

**Comment by ianrumac** [comment]
Hey @OrcunJoyoLabs !
Thanks for the report, we're investigating it and will release an update soon 🙏

**Comment by cihati** [comment]
@ianrumac @yusuftor wanted to kindly ping here, when do you guys plan to make a fix and release a new version?

**Comment by DaxeshV** [comment]
Hi @ianrumac,

I hope you’re doing well. I wanted to follow up regarding the ongoing issue with events not displaying. As a freelancer managing multiple clients, I’ve recommended Superwall for their projects, but this persistent issue is causing significant frustration for both my clients and myself.

Given that many of my clients are not technically inclined, it’s challenging to keep explaining the delay, and this has now been pending for over two weeks without a resolution.

I genuinely appreciate your support, but if this problem isn’t resolved soon, I may have to consider moving my clients to an alternative provider.

Thank you for your attention, and I look forward to your prompt response.

**Comment by yusuftor** [comment]
Hey, @DaxeshV and @cihati, we're working on this right now. It looks like there's been some data loss as we switched over to using pigeon within our code. We'll release an update fixing this hopefully later today.

**Comment by ianrumac** [comment]
Hi everyone,
we have released a new version 2.2.0 containing the fixes for the missing events

**Comment by OrcunJoyoLabs** [comment]
@ianrumac - 2.2.0 doesn't compile - SuperwallDelegate.swift has an extra comma - "," on name parameter..

**Comment by yusuftor** [comment]
Fixed in 2.2.1!

**Comment by OrcunJoyoLabs** [comment]
Folks @yusuftor @ianrumac this is still not fixed.. 

Transaction start and abandons are not sending product info.. 
Placement name value is null as well.. 


```
flutter: eventInfo: EventType.transactionStart
flutter: placementName: null
flutter: paywallInfo: Instance of 'PaywallInfo' 
flutter: product: null
